name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

defaults:
  run:
    shell: pwsh

jobs:
  ci:
    name: CI
    runs-on: Ubuntu-Latest
    strategy:
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Utilities
        run: sudo apt-get install -y cloc hunspell hunspell-en-gb

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
    
      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run Line Count Heuristic
        run: bash ./ci/loc.sh

      - name: Run Spell Check
        run: bash ./ci/spellcheck.sh

      - name: Run Linter
        run: poetry run ruff check .

      - name: Check Formatting
        run: poetry run ruff format --check .

      - name: Run Tests & Check Coverage
        run: bash ./ci/coverage.sh

  publish-dry-run:
    name: Publish (Dry-Run)
    runs-on: Ubuntu-Latest
    needs: [ci]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Publish (Dry-Run)
        run: poetry publish --build --dry-run
